# This file was generated by GoReleaser. DO NOT EDIT.
cask "sqlite2pg" do
  version "0.3.2"

  on_macos do
    on_arm do
      sha256 "2db0bb905bbbc83b3aa20553407180962ce719f48add6e9c410717d00ee403a5"
      url "https://github.com/barrettclark/sqlite2pg/releases/download/v#{version}/sqlite2pg_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "a0e8103a0807e4a087517ce46fd82272cbda7df37a7a6f940f285dd6526363dc"
      url "https://github.com/barrettclark/sqlite2pg/releases/download/v#{version}/sqlite2pg_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "63e623452e61bbd1f80f4c0b97f4fb4a909af3b8c9bf42b51d9afb9bb14ac036"
      url "https://github.com/barrettclark/sqlite2pg/releases/download/v#{version}/sqlite2pg_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "1b572bb87e4a0c662d47ff39bd4c4de78ed1d260721a1258755bc67595c507ba"
      url "https://github.com/barrettclark/sqlite2pg/releases/download/v#{version}/sqlite2pg_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sqlite2pg"
  desc "A pgloader replacement for migrating SQLite databases into PostgreSQL"
  homepage "https://github.com/barrettclark/sqlite2pg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sqlite2pg"

  # No zap stanza required
end
