# This file was generated by GoReleaser. DO NOT EDIT.
cask "sqlite2pg" do
  version "0.3.1"

  on_macos do
    on_arm do
      sha256 "1b7a61858f0fdfbda8fa2dafad3faef798677e586bc8c4719281080002f47a97"
      url "https://github.com/barrettclark/sqlite2pg/releases/download/v#{version}/sqlite2pg_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "dec52c134348a04512aedca1d09c5d8ed9c639f5601fb033a46ba5557afe9b6b"
      url "https://github.com/barrettclark/sqlite2pg/releases/download/v#{version}/sqlite2pg_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4ea12294c34411fe8cd04232e8e66d73a903b7e774ad1ea09b38e7c68383a3a9"
      url "https://github.com/barrettclark/sqlite2pg/releases/download/v#{version}/sqlite2pg_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "93d84b5197840def3214e12b7e6716f504f41743e7c2fef34e77a71078a1f1db"
      url "https://github.com/barrettclark/sqlite2pg/releases/download/v#{version}/sqlite2pg_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sqlite2pg"
  desc "A pgloader replacement for migrating SQLite databases into PostgreSQL"
  homepage "https://github.com/barrettclark/sqlite2pg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sqlite2pg"

  # No zap stanza required
end
