# This file was generated by GoReleaser. DO NOT EDIT.
cask "sqlite2pg" do
  version "0.3.0"

  on_macos do
    on_arm do
      sha256 "18e6598e76fb555a4502244784f2559bf8c9eae56f51acc3023a4e06e496598d"
      url "https://github.com/barrettclark/sqlite2pg/releases/download/v#{version}/sqlite2pg_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "5af83186db840a06ba7c834d1563780e8703e25f2d3e8c43dfa75fc75cf46120"
      url "https://github.com/barrettclark/sqlite2pg/releases/download/v#{version}/sqlite2pg_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "59b9adf4c75298de97afadd7d84f597603bccac7f133ef9c5b2bb4eaaa4f9497"
      url "https://github.com/barrettclark/sqlite2pg/releases/download/v#{version}/sqlite2pg_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "f4f134a9a5be2d22cf454584272afa738e4daa4f6ba046e3ce8afd0e455a3248"
      url "https://github.com/barrettclark/sqlite2pg/releases/download/v#{version}/sqlite2pg_#{version}_linux_amd64.tar.gz"
    end
  end

  name "sqlite2pg"
  desc "A pgloader replacement for migrating SQLite databases into PostgreSQL"
  homepage "https://github.com/barrettclark/sqlite2pg"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sqlite2pg"

  # No zap stanza required
end
