# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sqlite2pg < Formula
  desc "A pgloader replacement for migrating SQLite databases into PostgreSQL"
  homepage "https://github.com/barrettclark/sqlite2pg"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/barrettclark/sqlite2pg/releases/download/v0.2.1/sqlite2pg_0.2.1_darwin_amd64.tar.gz"
      sha256 "78f9f7538a786c54390a62eb7969cac91e89abbe2e931f6035f72a616ab657de"

      define_method(:install) do
        bin.install "migrate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/barrettclark/sqlite2pg/releases/download/v0.2.1/sqlite2pg_0.2.1_darwin_arm64.tar.gz"
      sha256 "6d34bbc04270905d3da1369a57edc703483b0afef8bff0f5f7d4c19ffff4c00f"

      define_method(:install) do
        bin.install "migrate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/barrettclark/sqlite2pg/releases/download/v0.2.1/sqlite2pg_0.2.1_linux_amd64.tar.gz"
      sha256 "0d1002cf6a33024a2e99b9cefd9e1c3dcbabd7f7c02895da8bc8b69f8bd51c2b"
      define_method(:install) do
        bin.install "migrate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/barrettclark/sqlite2pg/releases/download/v0.2.1/sqlite2pg_0.2.1_linux_arm64.tar.gz"
      sha256 "6685677bba716329a8af8a07c84677b79f4151f55099023aab5f74fbf89fc917"
      define_method(:install) do
        bin.install "migrate"
      end
    end
  end

  test do
    # migrate has no --help; a bare invocation exits 1 with a usage
    # message, which is the closest thing to a smoke test it offers.
    assert_match "usage: migrate", shell_output("#{bin}/migrate 2>&1", 1)
  end
end
